config/routes.rb
Rails.application.routes.draw do
  root to: "homes#show"
  resources :homes, only: [:show]
  resources :articles
  resources :announcements
  resources :lectures
  resources :teachers
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
    get  'user/new' => 'user#new'
    post 'user/new' => 'user#create'
  resources :user, :controller => "user"
  get '/dashboard' => 'dashboard#index'
  get '/user/edit' => 'user#edit'
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    if current_user.admin?
      @users = User.all
      @lectures = Lecture.all
      @teachers = Teacher.all
      @user = current_user
    else
      redirect_to root_path
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.haml
.container-fluid{class: "content_show_dash"}
  .col-lg-2{class: "actions"}
    .list-group
      .list-group-item
        = link_to 'New User', new_user_path, class: "btn btn-link"
      .list-group-item
        = link_to 'New Teacher', new_teacher_path, class: "btn btn-link"
      .list-group-item
        = link_to 'New Announcement', new_announcement_path, class: "btn btn-link"
      .list-group-item
        = link_to 'New Lecture', new_lecture_path, class: "btn btn-link"
      .list-group-item
        = link_to 'New Article', new_article_path, class: "btn btn-link"
  .col-lg-4{class: "users"}
    .container-fluid{class: "user"}
      .label-column
        %h4 Users:
      - @users.all.order("id desc").limit(10).each do |u|
        .user-actions
          %table{class: "table-responsive table-users"}
            %tbody
              %tr
                %td
                  = image_tag u.avatar, class: "img-circle user-av"
                  = u.name
                  = u.second_name
              %tr
                %td{class: "actonuser"}
                  = link_to 'Destroy', u, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-link"
                  = link_to 'Edit', edit_user_path(u), class: "btn btn-link"
                  = link_to 'Show', u, class: "btn btn-link"
  .col-lg-3{class: "tchres"}
    .container-fuid{class: "teachers"}
      .label-column
        %h4 Teachers:
      - @teachers.all.order("id desc").limit(10).each do |t|
        .teacher-actions
          %table{class: "table-responsive table-teachers"}
            %tbody
              %tr
                %td
                  = t.id
                  = t.name
              %tr
                %td{class: "actonuser"}
                  = link_to 'Destroy', t, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-link"
                  = link_to 'Edit', edit_teacher_path(t), class: "btn btn-link"
                  = link_to 'Show', t, class: "btn btn-link"
  .col-lg-3
    .container-fluid{class: "lectures"}
      .label-column
        %h4 Lectures:
      - @lectures.all.order("id desc").limit(10).each do |t|
        .lecture-actionss
          %table{class: "table-responsive table-lectures"}
            %tbody
              %tr
                %td
                  = t.id
                  = t.name
              %tr
                %td{class: "actonuser"}
                  = link_to 'Destroy', t, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-link"
                  = link_to 'Edit', edit_lecture_path(t), class: "btn btn-link"
                  = link_to 'Show', t, class: "btn btn-link"