config/routes.rb
Rails.application.routes.draw do
  root to: "homes#show"
  resources :homes, only: [:show]
  resources :articles
  resources :announcements
  resources :lectures
  resources :teachers
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
    get  'user/new' => 'user#new'
    post 'user/new' => 'user#create'
  resources :user, :controller => "user"
  get '/dashboard' => 'dashboard#index'
  get '/user/edit' => 'user#edit'
  end

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  has_many :announcements
  has_many :articles
  belongs_to :teacher
  mount_uploader :coverphoto, LectureCoverPhotoUploader
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:  [:edit, :update, :destroy, :create, :new]

  # GET /lectures
  def index
    @lectures = Lecture.all
    @teachers = Teacher.all
    @users = User.all
    @q = Lecture.ransack(params[:q])
    @lectures = @q.result(distinct: true)
    @list_user = @users.select{:email}
    @lectures.each do |lect|
      lect.ann_count=lect.announcements.size
      lect.save
    end
  end

  # GET /lectures/1
  def show
    @announcements = Announcement.all
    @ann_content = @lecture.announcements.select{:name}
  end

  # GET /lectures/new
  def new
    if current_user.admin?
      @lecture = Lecture.new
    else
      redirect_to root_path
    end
  end

  def anncount
    if @lecture.ann_count.nil?
      @lecture.ann_count = 0
    end
    @lecture.save
  end

  # GET /lectures/1/edit
  def edit
    if current_user.admin?
    else
      redirect_to root_path
    end
  end

  # POST /lectures
  def create
    if current_user.admin?
      @lecture = Lecture.new(lecture_params)

    if @lecture.save
      redirect_to lectures_path
    else
      render :new
    end
    else
      redirect_to root_path
      end
  end

  # PATCH/PUT /lectures/1
  def update
    if current_user.admin?
      if @lecture.update(lecture_params)
        redirect_to @lecture, notice: 'Lecture was successfully updated.'
      else
        render :edit
      end
    else
      redirect_to root_path
    end
  end

  # DELETE /lectures/1
  def destroy
    if current_user.admin?
      @lecture.destroy
      redirect_to lectures_url, notice: 'Lecture was successfully destroyed.'
    else
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def lecture_params
      params.require(:lecture).permit(:name, :teacher_id, :announcement_id, :coverphoto)
    end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.haml
= simple_form_for(@lecture) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.association :teacher
    = f.file_field :coverphoto

  .form-actions
    = f.button :submit

app/views/lectures/edit.html.haml
%h1 Editing lecture

= render 'form'

= link_to 'Show', @lecture
\|
= link_to 'Back', lectures_path

app/views/lectures/index.html.haml
%html
  %body
    .container-fluid{class: "content_show_home"}
      .row
        .col-lg-6
          .container-fluid{class: "listing"}
            - @lectures.each do |lecture|
              .list_lect
                %table{class:"table-hover table-responsive tablestyle"}
                  %tbody
                    %tr
                      %td= link_to lecture.name, lecture, :action => :show, class: "btn btn-link"
          .col-lg-6

app/views/lectures/new.html.haml
%h1 New lecture

= render 'form'

= link_to 'Back', lectures_path

app/views/lectures/show.html.haml
.container-fluid{ class: "lecturecoverphoto"}
  .navbar-brand{class: "name-lecture"}
    .container-fluid
      .list-inline
        = @lecture.name
  = image_tag @lecture.coverphoto, class: "coverimage"
  .navbar-default{class: "lecture-actions"}
    .container-fluid
      = link_to 'Announcements', announcement_path, class: "btn btn-link btn-md"
.container-fluid{class: "feed"}
  - @announcements.where(:lecture => @lecture).last(3).each  do |anno|
    .list_announcement
      = image_tag anno.annphoto, class:"thumb"
      %table{class:"table-hover table-responsive table-announcement"}
        %tbody
          %tr
            %td= link_to anno.title, anno, :action => :show, class: "btn btn-link"
          %tr
            %td= sanitize (anno.content.truncate(300, separator: '</p>'))
          %tr
            %td= anno.lecture.name
.col-lg-5