config/routes.rb
Rails.application.routes.draw do
  root to: "homes#show"
  resources :homes, only: [:show]
  resources :articles
  resources :announcements
  resources :lectures
  resources :teachers
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
    get  'user/new' => 'user#new'
    post 'user/new' => 'user#create'
  resources :user, :controller => "user"
  get '/dashboard' => 'dashboard#index'
  get '/user/edit' => 'user#edit'
  end

end

app/views/layouts/application.html.haml
%html
  %head
    %title=Moodle
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if user_signed_in?
      - if current_user.admin?
        .navbar-default{class: "admin_nav"}
          .container-fluid{class: "admin-welcome"}
            .col-lg-4
              %table{class: "activeadmin"}
                %tbody
                  %tr
                    %td
                      = link_to "Dashboard", dashboard_path, class: "btn btn-link btn-dash btn-xs"
                    %td
                      = link_to 'New User', new_user_path, class: "btn btn-link btn-dash btn-xs"
                    %td
                      = link_to 'New Teacher', new_teacher_path, class: "btn btn-link btn-dash btn-xs"
                    %td
                      = link_to 'New Announcement', new_announcement_path, class: "btn btn-link btn-dash btn-xs"
                    %td
                      = link_to 'New Lecture', new_lecture_path, class: "btn btn-link btn-dash btn-xs"
                    %td
                      = link_to 'New Article', new_article_path, class: "btn btn-link btn-dash btn-xs"
      - else
    -else
    .navbar-default{class: "main_nav"}
      .container-fluid
        .col-lg-4
          %table{class: "table-responsive table-menu"}
            %tbody
              %tr
                %td= link_to "Home", root_path, class: "btn btn-link"
                %td= link_to "Lectures", lectures_path, class: "btn btn-link"
                %td= link_to "Teachers", teachers_path, class: "btn btn-link"
                %td= link_to "Announcements", announcements_path, class: "btn btn-link"
        .col-lg-6
        .col-lg-2
          .container-fluid{class: "session"}
            - if user_signed_in?
              .pull-right
                = link_to('Log Out', destroy_user_session_path, :method => :delete, class:"btn btn-link log_out")
                = image_tag current_user.avatar, class: "thumb-user"
            -else
              .pull-right
                = link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), class: "btn btn-facebook"
    .container-fluid{class: "content-area"}
      = yield
    .container-fluid{class:"footer"}
      .container-fluid{class: "copyright"}